easy_admin:
    entities:
#        # List the entity class name you want to manage
        Site:
            class: App\Entity\Site
            label: 'Sites'
            list:
                title: "Liste sites"
                fields:
                    - id
                    - name
                    - alias
                    - content
                    - image
                    -  { property: 'category', type: 'entity', type_options: { class: 'App\Entity\Category', multiple: false } }
        Course:
            class: App\Entity\Course
            label: 'Parcours'
            list:
                title: "Liste parcours"
                fields: ['id', 'category_id', 'name', 'duration', 'priority', 'steps']
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                title: "Liste utilisateurs"
                fields: ['id', 'pseudo', 'email', 'password']

    site_name: 'DiscoverMyIsland'

    user:
        display_name: true
        display_avatar: false
        name_property_path: 'fullName'
        avatar_property_path: 'gravatar'

    design:

    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'


