default_index:
    path: /
    controller: App\Controller\DefaultController::index

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /adminDMI
    type: annotation



