default_index:
    path: /
    controller: App\Controller\DefaultController::index

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /_dmi_backend
    type: annotation

